Vagrant.configure("2") do |config|

  # Ubuntu 16.04 operating system.
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Telegraf UDP port.
  config.vm.network "forwarded_port", guest: 8125, host: 8125, host_ip: "127.0.0.1", protocol: "udp"

  # Chronograf HTTP port.
  config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1", protocol: "tcp"

  config.vm.provision "shell", inline: <<-SHELL

    # Telegraf, InfluxDB, Chronograf - Install and configure.
    curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    source /etc/lsb-release
    echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
    apt-get -y update
    apt-get -y install influxdb telegraf
    wget https://dl.influxdata.com/chronograf/releases/chronograf_1.5.0.0_amd64.deb -q -O /tmp/chronograf.deb
    dpkg -i /tmp/chronograf.deb
    cp /vagrant/vagrant/telegraf_statsd.conf /etc/telegraf/telegraf.d/statsd.conf
    systemctl start influxdb
    systemctl start telegraf
    systemctl start chronograf

  SHELL
end
